#!/bin/bash

# Variables definations
RELEASE_BRANCH=master
DEPLOY_BRANCH=gh-pages
DIST_FOLDER=dist
TEMP_FOLDER=.built_website

TARGET_REPO=$(git config --get remote.origin.url)
LAST_MESSAGE=$(git log -1 origin/$RELEASE_BRANCH --oneline)
DIST_FOLDER_PATH=$(realpath "$DIST_FOLDER")
TEMP_FOLDER_PATH=$(realpath "$TEMP_FOLDER")

echo -e "Git repository: $TARGET_REPO"
echo -e "Distributed path: $DIST_FOLDER_PATH"
echo -e "Temporary path: $TEMP_FOLDER_PATH"

# Switch release branch
git checkout $RELEASE_BRANCH || exit 0;
git pull origin $RELEASE_BRANCH || exit 0;

if [ -d $DIST_FOLDER_PATH ]; then
  echo -e "Deploy to product environment\n"

  # Clean or create temporary directory
  if [ -d $TEMP_FOLDER_PATH ]; then
    rm -rf $TEMP_FOLDER_PATH
  fi

  mkdir $TEMP_FOLDER_PATH
  cd $TEMP_FOLDER_PATH

  # Clone pero and switch branch
  git init
  git remote add origin $TARGET_REPO
  git checkout $DEPLOY_BRANCH || git checkout -b $DEPLOY_BRANCH || exit 0;

  # Copy data we're interested in to that directory
  rsync -rv --exclude=.git $DIST_FOLDER_PATH/* . || exit 0;

  # Add, commit and push files
  git add -f .
  git commit -m "($LAST_MESSAGE) Deploy branch $RELEASE_BRANCH to $TARGET_REPO:$DEPLOY_BRANCH"
  git push -fq origin $DEPLOY_BRANCH > /dev/null || exit 0;

  echo -e "Deployment completed.\n"
else
  echo -e "Folder $DIST_FOLDER_PATH does not exist\n"
fi
